### ISSUE TITLE
State that implicit preferred algorithm lists exist even when the corresponding subpacket is missing

### ISSUE THREAD

**Issue by falko-strenzke** [openpgp-pqc/draft-openpgp-pqc#106]
Regarding the "Preferred AEAD Ciphersuites" subpacket and "Preferred Symmetric Ciphers for v1 SEIPD" subpacket, we need a clarification in Sec. "8.1. Symmetric Algorithms for SEIPD Packets". The crypto-refresh does not clearly state that the implicit lists of preferred algorithms are in force even when the respective subpacket is missing. We should clarify this at least in the PQC specification.

**Comment by dkg** [comment]
I'm not sure how much this draft needs to fix this.  But at a maximum, what we need to say is "a certificate with no AEAD Ciphersuite Preferences subpacket should be treated the same as an otherwise-identical certificate with an present-but-empty AEAD Ciphersuite Preferences subpacket".  However, framed this way it does seem like this is something that belongs in the primary specification, and not as a clarification in the PQC draft.

What other interpretation is possible, which a wayward implementer might actually consider?
