### ISSUE TITLE
Composite signature domain separators?

### ISSUE THREAD

**Issue by ounsworth** [openpgp-pqc/draft-openpgp-pqc#133]
Within the LAMPS composite sigs, we have:

```
M' := Domain || HASH(Message)

S1 := Sign( K1, A1, M' )
S2 := Sign( K2, A2, M' )
```
where `Domain` is the `DER( Composite_OID )`. The intent is so that S1 and S2 will not verify over `HASH(Message)` directly, but only over `DER( Composite_OID ) || HASH(Message)`. This achieves Strong Non-Separability as per Hale-Connolly.

Is there a reason that you are not doing this for your composite signature?

**Comment by falko-strenzke** [comment]
In OpenPGP Strong Non-Separability is achieved in without any additional measures, since OpenPGP hashes the signature algorithm identifier as part of the meta data in the signature digest. Thus changing the signature algorithm in the signature packet causes a signature to which no message can be found.

**Comment by falko-strenzke** [comment]
@ounsworth  Is it OK if we close this issue?
